export const GAME_STATE_PLAYER_SELECTION = "GAME_STATE_PLAYER_SELECTION"
export const GAME_STATE_GAME_SELECTION = "GAME_STATE_GAME_SELECTION"
export const GAME_STATE_BOARD = "GAME_STATE_BOARD"
export const GAME_STATE_LOADING = "GAME_STATE_LOADING"
export const GAME_STATE_QUESTION = "GAME_STATE_QUESTION"
export const GAME_STATE_ASSIGN_POINTS = "GAME_STATE_ASSIGN_POINTS"
export const GAME_STATE_GAME_OVER = "GAME_STATE_GAME_OVER"

export const SWITCH_GAME_STATE = "SWITCH_GAME_STATE"
export const switchGameState = (newState) => ({
  type: SWITCH_GAME_STATE,
  state: newState
})
